name: sahaayak
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.1.0
  dart_openai: ^5.1.0 
  youtube_player_flutter: ^9.1.0
  cached_network_image: ^3.3.1
  google_generative_ai: ^0.4.0
  flutter_sound: ^9.2.13
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  intl: ^0.19.0
  speech_to_text:  ^7.0.0
  flutter_tts: ^4.0.2
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  video_player: ^2.8.6
  cupertino_icons: ^1.0.8
  fl_chart: ^1.1.1
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.4"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/asha.png
    - assets/calm_wave.svg
    - assets/videos/intro_video.mp4